### ISSUE TITLE
Docker-desktop can't create and mount folder

### ISSUE THREAD

**Issue by retspen** [docker/desktop-linux#17]
- [ x ] I have tried with the latest version of Docker Desktop
  - [ x ] I have tried disabling enabled experimental features
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 79765c06-b30c-47cd-8369-b2a465fbe7d3/20220513192903

### Expected behavior

Created folder `.mysql` with data from the container.

### Actual behavior

The folder was not created locally but docker inspect in menu Mounts shows the folder mounted inside docker desktop virtual machine.

![image](https://user-images.githubusercontent.com/688722/168379132-6134803d-d029-4638-aa3d-d715497fee7f.png)

If I create empty folder `.mysql` with permission 777 manually I got the next error:

`chown: changing ownership of '/var/lib/mysql/': Invalid argument`

### Information

  - Linux distro: Fedora
  - Distro version: 36
  - Docker Desktop Version: 4.8.1-78998

### Steps to reproduce the behavior

Docker-compose file:
```
version: '3.7'
services:
   mariadb:
     image: mariadb:10.5.13
     hostname: "mariadb"
     volumes:
     - ./.mysql:/var/lib/mysql
     ports:
     - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
```
