### ISSUE TITLE
Container generated files gets wrong uid & gid on host machine

### ISSUE THREAD

**Issue by ARehmanMahi** [docker/desktop-linux#31]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2f8f483e-e3ac-44f2-a1e6-8e6a31f5a6a2/20220618200955

### Expected behavior

Container service generated files should have same uid on host 

### Actual behavior

Container service generated files have weird/wrong uid on host 

### Information

  - Linux distro: Ubuntu
  - Distro version: 22.04
  - Docker Desktop Version: 4.9.1

Container generated files gets wrong uid & gid on host machine, even though container service in this case php-fpm has 1000 uid for user as defined in the docker file, details below.

I did a chown 1000:1000 on `storage` folder inside container, and after that I get the issue

![Screenshot from 2022-06-19 01-26-35](https://user-images.githubusercontent.com/3149876/174456157-fde0cfc5-50bd-4f07-ab04-be2846b69738.png)

docker-compose 

```
version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker-files/php.dockerfile
            args:
                - user=jenkins
                - group=www-data
                - uid=1000
        container_name: php
        volumes:
            - .:/var/www/html/
        working_dir: /var/www/html/

    nginx:
        build:
            context: .
            dockerfile: docker-files/nginx.dockerfile
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        working_dir: /var/www/html/
        extra_hosts:
            - "laravel-app.test:127.0.0.1"
        depends_on:
            - php
```

php.dockerfile
```
FROM php:8.1-fpm-alpine

ARG user
ARG group
ARG uid

RUN addgroup $user
RUN adduser -D -H -u $uid $user -G $user -s /bin/sh

RUN sed -i "s/user[ \t]*=[ \t]*www-data/user = $user/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group[ \t]*=[ \t]*www-data/group = $group/g" /usr/local/etc/php-fpm.d/www.conf
```
